version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.slim
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/tododb
    depends_on:
      - mongodb
    volumes:
      - ./:/app
    networks:
      - todo-network

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - todo-network

volumes:
  mongodb_data:
    driver: local

networks:
  todo-network:
    driver: bridge